name: CI

on:
  push:
    branches:
      - xcode-build
  workflow_dispatch:  # This allows manual triggering

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Build project
      run: xcodebuild -project transmission/transmission.xcodeproj -scheme YourSchemeName -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro' clean build | xcpretty
