name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Fix Script Permissions
        run: |
          chmod +x /Users/runner/Library/Developer/Xcode/DerivedData/Transmission-heesbguwjjmasidhwvitbwbyojzr/Build/Intermediates.noindex/Transmission.build/Debug/psl.build/Script-C3D9062C27B7F4FE00EF2386.sh
          chmod +x /Users/runner/Library/Developer/Xcode/DerivedData/Transmission-heesbguwjjmasidhwvitbwbyojzr/Build/Intermediates.noindex/Transmission.build/Debug/miniupnp.build/Script-A2305097100C0293003FDB0C.sh
      - name: Clean project
        run: xcodebuild clean -project Transmission.xcodeproj
      - name: Use Legacy Build System
        run: xcodebuild -project Transmission.xcodeproj -scheme Transmission -UseModernBuildSystem=NO
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
